"""Combine current FIR model-family evaluator results.

The individual experiments are useful, but for the thesis we need one summary:

- baseline FSPS
- empirical FSPS/ALESS hybrids
- pure ALESS
- simple modified-blackbody temperature grid

This script does not recompute fluxes. It just combines the evaluator outputs
that were already generated by:

- popcosmos_differential_count_evaluator.py
- popcosmos_mbb_temperature_grid.py
"""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


NB_DIR = Path(__file__).resolve().parent
OUT_DIR = NB_DIR / "outputs"

HYBRID_POOLED = OUT_DIR / "popcosmos_differential_count_evaluator_pooled_summary.csv"
HYBRID_REGIME = OUT_DIR / "popcosmos_differential_count_evaluator_regime_summary.csv"
MBB_POOLED = OUT_DIR / "popcosmos_mbb_temperature_grid_pooled_summary.csv"
MBB_REGIME = OUT_DIR / "popcosmos_mbb_temperature_grid_regime_summary.csv"
CASEY_POOLED = OUT_DIR / "popcosmos_casey_like_template_grid_pooled_summary.csv"
CASEY_REGIME = OUT_DIR / "popcosmos_casey_like_template_grid_regime_summary.csv"


REGIME_LABELS = {
    "all_scored_counts": "all scored counts",
    "resolved_or_prior_counts_only": "resolved/prior counts",
    "pd_statistical_counts_only": "P(D) statistical counts",
    "resolved/prior": "resolved/prior counts",
    "P(D) statistical": "P(D) statistical counts",
}


def family_from_hybrid_label(label):
    if label == "FSPS":
        return "baseline"
    if label == "ALESS":
        return "empirical template"
    return "FSPS/ALESS hybrid"


def combine_pooled():
    cols = [
        "regime",
        "model_family",
        "model_key",
        "model_label",
        "T_dust_K",
        "N_points",
        "chi2_log",
        "median_log10_model_over_obs",
        "reduced_chi2_log",
    ]

    hybrid = pd.read_csv(HYBRID_POOLED)
    hybrid["model_family"] = hybrid["model_label"].map(family_from_hybrid_label)
    hybrid["model_key"] = hybrid["model_label"]
    hybrid["T_dust_K"] = np.nan
    hybrid["regime"] = "all scored counts"

    mbb = pd.read_csv(MBB_POOLED)
    mbb["model_label"] = mbb["T_dust_K"].map(lambda t: f"MBB {int(t)} K")
    mbb["model_family"] = "modified blackbody"
    mbb["model_key"] = mbb["model"]
    mbb["regime"] = "all scored counts"

    pieces = [hybrid[cols], mbb[cols]]

    if CASEY_POOLED.exists():
        casey = pd.read_csv(CASEY_POOLED)
        casey["model_family"] = "Casey-like template"
        casey["model_key"] = casey["model"]
        casey["regime"] = "all scored counts"
        pieces.append(casey[cols])

    out = pd.concat(pieces, ignore_index=True)
    return out.sort_values("reduced_chi2_log")


def combine_regime():
    cols = [
        "regime",
        "model_family",
        "model_key",
        "model_label",
        "T_dust_K",
        "N_points",
        "chi2_log",
        "median_log10_model_over_obs",
        "reduced_chi2_log",
    ]

    hybrid = pd.read_csv(HYBRID_REGIME)
    hybrid = hybrid[hybrid["regime"] != "all_scored_counts"].copy()
    hybrid["regime"] = hybrid["regime"].map(REGIME_LABELS)
    hybrid["model_family"] = hybrid["model_label"].map(family_from_hybrid_label)
    hybrid["model_key"] = hybrid["model"]
    hybrid["T_dust_K"] = np.nan

    mbb = pd.read_csv(MBB_REGIME)
    mbb["regime"] = mbb["count_regime"].map(REGIME_LABELS)
    mbb["model_label"] = mbb["T_dust_K"].map(lambda t: f"MBB {int(t)} K")
    mbb["model_family"] = "modified blackbody"
    mbb["model_key"] = mbb["model"]

    pieces = [hybrid[cols], mbb[cols]]

    if CASEY_REGIME.exists():
        casey = pd.read_csv(CASEY_REGIME)
        casey["regime"] = casey["count_regime"].map(REGIME_LABELS)
        casey["model_family"] = "Casey-like template"
        casey["model_key"] = casey["model"]
        pieces.append(casey[cols])

    out = pd.concat(pieces, ignore_index=True)
    return out.sort_values(["regime", "reduced_chi2_log"])


def make_best_summary(pooled, regime):
    rows = []
    rows.append({"regime": "all scored counts", **pooled.iloc[0].to_dict()})
    for regime_name, group in regime.groupby("regime"):
        rows.append({"regime": regime_name, **group.sort_values("reduced_chi2_log").iloc[0].to_dict()})
    out = pd.DataFrame(rows)
    return out[
        [
            "regime",
            "model_family",
            "model_label",
            "N_points",
            "reduced_chi2_log",
            "median_log10_model_over_obs",
        ]
    ]


def plot_combined(pooled, regime):
    family_colors = {
        "baseline": "#0072B2",
        "FSPS/ALESS hybrid": "#56B4E9",
        "empirical template": "#E69F00",
        "modified blackbody": "#009E73",
        "Casey-like template": "#CC79A7",
    }

    ranked = pooled.sort_values("reduced_chi2_log", ascending=True).copy()
    anchor_labels = ["FSPS", "ALESS", "25% ALESS", "50% ALESS", "MBB 35 K"]
    pooled_plot = pd.concat(
        [
            ranked.head(12),
            ranked[ranked["model_label"].isin(anchor_labels)],
        ],
        ignore_index=True,
    ).drop_duplicates(subset=["model_label"])
    pooled_plot = pooled_plot.sort_values("reduced_chi2_log", ascending=True)
    y = np.arange(len(pooled_plot))

    fig, axes = plt.subplots(1, 2, figsize=(13.5, 5.2))

    axes[0].barh(
        y,
        pooled_plot["reduced_chi2_log"],
        color=[family_colors.get(f, "0.5") for f in pooled_plot["model_family"]],
    )
    axes[0].set_yticks(y)
    axes[0].set_yticklabels(pooled_plot["model_label"], fontsize=8)
    axes[0].invert_yaxis()
    axes[0].set_xscale("log")
    axes[0].set_xlabel(r"rough reduced $\chi^2$")
    axes[0].set_title("All external differential counts")
    axes[0].grid(True, axis="x", which="both", alpha=0.25)

    for i, row in pooled_plot.iterrows():
        axes[0].text(
            row["reduced_chi2_log"] * 1.04,
            np.where(pooled_plot.index == i)[0][0],
            f"{row['reduced_chi2_log']:.2f}",
            va="center",
            fontsize=7,
        )

    top_models = ["Casey T30K a=3.0", "Casey T30K a=2.5", "25% ALESS", "MBB 35 K", "FSPS", "ALESS"]
    regime_plot = regime[regime["model_label"].isin(top_models)].copy()
    regime_order = ["resolved/prior counts", "P(D) statistical counts"]
    marker_lookup = {
        "25% ALESS": "o",
        "50% ALESS": "s",
        "MBB 35 K": "^",
        "FSPS": "D",
        "ALESS": "v",
        "Casey T30K a=3.0": "P",
        "Casey T30K a=2.5": "X",
    }
    for label, group in regime_plot.groupby("model_label"):
        vals = []
        for reg in regime_order:
            sub = group[group["regime"] == reg]
            vals.append(float(sub["reduced_chi2_log"].iloc[0]) if not sub.empty else np.nan)
        axes[1].plot(
            regime_order,
            vals,
            marker=marker_lookup.get(label, "o"),
            lw=1.8,
            label=label,
        )
    axes[1].set_yscale("log")
    axes[1].set_ylabel(r"rough reduced $\chi^2$")
    axes[1].set_title("Key models split by count type")
    axes[1].grid(True, axis="y", which="both", alpha=0.25)
    axes[1].legend(fontsize=8)
    axes[1].tick_params(axis="x", rotation=12)

    fig.suptitle("Current FIR model-family evaluator summary")
    fig.tight_layout(rect=[0, 0, 1, 0.93])
    path = OUT_DIR / "popcosmos_model_family_score_comparison.png"
    fig.savefig(path, dpi=180)
    plt.close(fig)
    return path


def main():
    pooled = combine_pooled()
    regime = combine_regime()
    best = make_best_summary(pooled, regime)

    pooled_path = OUT_DIR / "popcosmos_model_family_score_summary.csv"
    regime_path = OUT_DIR / "popcosmos_model_family_regime_summary.csv"
    best_path = OUT_DIR / "popcosmos_model_family_best_by_regime.csv"
    plot_path = plot_combined(pooled, regime)

    pooled.to_csv(pooled_path, index=False)
    regime.to_csv(regime_path, index=False)
    best.to_csv(best_path, index=False)

    print(pooled_path)
    print(regime_path)
    print(best_path)
    print(plot_path)
    print("\nOverall ranking:")
    print(pooled[["model_family", "model_label", "N_points", "reduced_chi2_log", "median_log10_model_over_obs"]].to_string(index=False))
    print("\nBest by regime:")
    print(best.to_string(index=False))


if __name__ == "__main__":
    main()
